development: redis://127.0.0.1:6379
test: redis://10.1.234.78:6379
production: redis://10.1.234.78:6379
 #unix:/var/run/redis/redis.sock
#
#development: redis://localhost:6379
#test: redis://localhost:6379
#production: redis://localhost:6379